---
- name: Get os_version from /etc/os-release
  ansible.builtin.raw: "grep '^VERSION_ID=' /etc/os-release | sed s'/VERSION_ID=//'"
  register: os_version
  check_mode: false
  changed_when: false

- name: Get distro name from /etc/os-release
  ansible.builtin.raw: "grep '^NAME=' /etc/os-release | sed s'/NAME=//'"
  register: distro
  check_mode: false
  changed_when: false

- name: Init the is_coreos fact
  ansible.builtin.set_fact:
    is_coreos: false

- name: Set the is_coreos fact
  ansible.builtin.set_fact:
    is_coreos: true
  when: "'CoreOS' in distro.stdout"

- name: Set the bin directory path for CoreOS
  ansible.builtin.set_fact:
    bin_dir: "/opt/bin"
  when: is_coreos

- ansible.builtin.include_tasks:
    file: coreos.yml
  when: is_coreos

- name: Determine if Atomic
  ansible.builtin.raw: "test -f /run/ostree-booted"
  register: s
  changed_when: false
  failed_when: false
  check_mode: false

- name: Set the is_atomic fact
  ansible.builtin.set_fact:
    is_atomic: true
  when: s.rc == 0

- ansible.builtin.include_tasks:
    file: fedora-dnf.yml
  when: 'os_version.stdout|int >= 22 and "Fedora" in distro.stdout and is_atomic is not defined'

- ansible.builtin.include_tasks:
    file: debian.yml
  when: '"Debian" in distro.stdout or "Ubuntu" in distro.stdout'
